# Use official Node.js image as base
FROM node:18

# Set working directory in the container
WORKDIR /app/server

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the client application
COPY . .

# Build the React app
EXPOSE 4000
CMD [ "npm","run","start" ]
